# Generated by Django 6.0.3 on 2026-04-06 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
