# Generated by Django 6.0.3 on 2026-04-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='CourseMetaData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
